# Generated by Django 3.2.7 on 2021-09-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_shippingaddress_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='date_added',
            new_name='dateAdded',
        ),
    ]
