# Generated by Django 3.2.7 on 2021-09-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_date_added_shippingaddress_dateadded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='dateAdded',
        ),
    ]
